---
title: "Basic_Pipeline_Stats"
author: "Audrey Bourret"
date: "21/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path(here::here(), "01_Code", "Functions", "get.value.R"))
library(tidyverse)

setwd(here::here())

LOCUS <- stringr::str_split(get.value("Loci"), pattern = ";")[[1]]
```

## Dataset description


```{r echo=FALSE, message=FALSE, warning=FALSE}
data.info <- readr::read_csv(file.path(here::here(), "00_Data", "00_FileInfos", "SeqInfo.csv") )
data.info %>% group_by(ID_projet, Loci, Type_echantillon) %>% 
              summarise(N = n()) %>% 
              pivot_wider(names_from = Type_echantillon, values_from = N)

```

## Stats

```{r nreads, echo=FALSE, message=FALSE, warning=FALSE}
cutadapt.res <- read_csv(file.path(here::here(), "00_Data", "02a_Cutadapt", "log", "Cutadapt_Stats.csv"))

esv.res <- read_csv(file.path(here::here(), "00_Data", "03b_SeqTab_dada2", "ESVtab_Stats.csv"))

dada2.summary <- data.frame()

for(l in LOCUS){
  
  dada2.int <- readr::read_csv(file.path(here::here(), "00_Data", "02b_Filtered_dada2", "log", paste0(l, "_dada2_summary.csv"))) 
  dada2.int <- dada2.int %>% mutate(Loci = l)
  dada2.summary <- bind_rows(dada2.summary, dada2.int)
  
}
         
dada2.summary <- dada2.summary %>% mutate(Dada2 = reads.out,
                                          Adapt = reads.in
                                          ) %>% 
  select(-c(reads.in, reads.out))


nreads.res <- cutadapt.res %>% left_join(dada2.summary %>%mutate( ID_labo = ID %>% str_remove(paste(paste0("_", LOCUS), collapse = "|"))) %>%
select(ID_labo, Loci, Dada2)) %>% 
                              left_join(esv.res)

nreads.res %>% pivot_longer(c(Raw, Adapt, Dada2, Merge, Final), names_to = "Step", values_to = "Nreads") %>%
                 mutate(Nreads = ifelse(is.na(Nreads), 0, Nreads),
                        Nreads1 = Nreads + 1 ,
                        Step = factor(Step, levels = c("Raw", "Adapt", "Dada2", "Merge", "Final"))) %>% 
                 left_join(data.info %>% select(ID_labo, Loci, ID_projet, Type_echantillon), 
                           by = c("ID_labo", "Loci")) %>% 
                 ggplot(aes(x = Step, y = Nreads1, col = Type_echantillon, group = ID_labo)) +
  #geom_jitter(height = 0) +
  geom_point() +
  geom_line() + 
  #geom_boxplot() +
  scale_y_continuous(trans="log10") +
  facet_grid(~Loci) +
    labs(y = "N reads + 1 (log)", x = "Pipeline step")+ 
  theme_bw()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```


