---
title: "Visualization tools 1"
author: "Audrey Bourret"
date: "17/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())

source(file.path(here::here(), "01_Code", "Functions", "get.value.R"))
library(tidyverse)

LOCUS <- stringr::str_split(get.value("Loci", file = file.path(here::here(), "Options.txt")), pattern = ";")[[1]]

```
## Dataset description

```{r echo=FALSE, message=FALSE, warning=FALSE}
data.info <- readr::read_csv(file.path(here::here(), "00_Data", "00_FileInfos", "SeqInfo.csv") )
data.info %>% group_by(ID_projet, Loci, Type_echantillon) %>% 
              summarise(N = n()) %>% 
              pivot_wider(names_from = Type_echantillon, values_from = N) %>% 
              knitr::kable()



```

## Change in N reads trough pipeline

```{r nreads, echo=FALSE, message=FALSE, warning=FALSE}
cutadapt.res <- read_csv(file.path(here::here(), "00_Data", "02a_Cutadapt", "log", "Cutadapt_Stats.csv"))

esv.res <- read_csv(file.path(here::here(), "00_Data", "03b_SeqTab_dada2", "ESVtab_Stats.csv"))

dada2.summary <- data.frame()

for(l in LOCUS){
  
  dada2.int <- readr::read_csv(file.path("00_Data", "02b_Filtered_dada2", "log", paste0(l, "_dada2_summary.csv"))) 
  dada2.int <- dada2.int %>% mutate(Loci = l)
  dada2.summary <- bind_rows(dada2.summary, dada2.int)
  
}
         
dada2.summary <- dada2.summary %>% mutate(Dada2 = reads.out,
                                          Adapt = reads.in
                                          ) %>% 
  select(-c(reads.in, reads.out))


nreads.res <- cutadapt.res %>% left_join(dada2.summary %>%mutate( ID_labo = ID %>% str_remove(paste(paste0("_", LOCUS), collapse = "|"))) %>%
select(ID_labo, Loci, Dada2)) %>% 
                              left_join(esv.res) %>% 
               pivot_longer(c(Raw, Adapt, Dada2, Merge, Final), names_to = "Step", values_to = "Nreads") %>%
                 mutate(Nreads = ifelse(is.na(Nreads), 0, Nreads),
                        Nreads1 = Nreads + 1 ,
                        Step = factor(Step, levels = c("Raw", "Adapt", "Dada2", "Merge", "Final"))) %>% 
                 left_join(data.info %>% select(ID_labo, Loci, ID_projet, Type_echantillon), 
                           by = c("ID_labo", "Loci")) 

nreads.res %>% ggplot(aes(x = Step, y = Nreads1, col = Type_echantillon, group = ID_labo)) +
  #geom_jitter(height = 0) +
  geom_point() +
  geom_line() + 
  #geom_boxplot() +
  scale_y_continuous(trans="log10") +
  facet_grid(~Loci) +
    labs(y = "N reads + 1 (log)", x = "Pipeline step", title = "N reads throughout pipeline steps")+ 
  theme_bw()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

## N read in samples vs controls

```{r echo=FALSE, message=FALSE, warning=FALSE}
nreads.res %>% filter(Step == "Final") %>% 
  ggplot(aes(x = Type_echantillon, y = Nreads1, col = Type_echantillon)) +
  geom_jitter(height = 0) +
  geom_boxplot() +
  scale_y_continuous(trans="log10") +
  facet_grid(~Loci) +
    labs(y = "N reads + 1 (log)", x = "Sample type", title = "Boxplot of N reads in samples vs controls")+ 
  theme_bw()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

```
## N MOTUS vs reads

To have an idea if the sequencing depth is OK

```{r echo=FALSE, message=FALSE, warning=FALSE}

ESV.table <- data.frame(ID_labo = character(),
                        SEQ = character(),
                        Nreads = numeric(),
                        Loci = character(),
                        stringsAsFactors = F)

  
for(l in LOCUS){
  
  esv.path <- file.path(here::here(), "00_Data", "03c_ESV", paste0("ESV.", l, "_table.txt"))
  
  seq.int <- readr::read_delim(esv.path, delim = " ", col_names = F, n_max = 1) %>% as.vector()
  esv.int <- readr::read_delim(esv.path, delim = " ", col_names = F, skip = 1) 
  names(esv.int) <- c("ID_labo", seq.int)
  esv.int <- esv.int %>% pivot_longer(-ID_labo, names_to = "SEQ", values_to = "Nreads") %>% 
                         mutate(Loci = l)
  
  ESV.table <- bind_rows(ESV.table, esv.int)

}
  
#str(ESV.table)

ESV.table <- ESV.table %>% left_join(data.info %>% select(ID_labo, ID_projet, Loci, Type_echantillon))

ESV.table.summary <- ESV.table %>% group_by(ID_labo, Loci, Type_echantillon) %>% 
              summarise(NESV = length(SEQ[Nreads > 0]),
                        Nreads = sum(Nreads)) 

ESV.table.summary %>% ggplot(aes(y = NESV, x = Nreads, col = Type_echantillon)) +
                    geom_point() +
    scale_y_continuous(trans="log10") +
  facet_wrap(~Loci) +
  geom_smooth(method = "loess") +
  theme_bw()

```



## Visualization by plate and loci

```{r echo=FALSE, message=FALSE, warning=FALSE}

plate.data <- data.info %>% left_join(esv.res) %>% mutate(Plate_row = str_sub(ID_puit,1,1),
                                                          Plate_col = ID_puit %>% str_remove(Plate_row),
                                                          Nread.cor = Final + 1)


for(x in LOCUS){

g1 <- plate.data %>% filter(Loci == x) %>% 
    ggplot(aes(x = Plate_col, y = Plate_row )) + 
    geom_bin2d(aes(fill = Final)) +
    geom_point(aes(shape = Type_echantillon, size = Type_echantillon)) +
    scale_fill_distiller(palette = "Spectral", trans = "log10", na.value = "white") +
    #scale_fill_gradient(low = "darkgray", high = "red", trans = "log") +
    scale_y_discrete() +
    labs(x ="Row", y = "Column", title = x) +
    guides(fill = guide_colourbar(title = "N reads", title.hjust = 0)) + 
    facet_wrap(~ ID_plaque) +
    theme_bw()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          axis.ticks.y = element_blank(), legend.position = "right") 

print(g1)
}

```

## Sequencing depth

To find a minimum threshold

```{r echo=FALSE, message=FALSE, warning=FALSE}
nreads.res %>% filter(Step == "Final") %>% 
  ggplot(aes(x = Nreads1, fill = Type_echantillon)) +
  geom_histogram() +
  scale_x_continuous(trans="log10") +
  facet_wrap(~Loci) +
    labs(x = "N reads + 1 (log)", title = "Histogram of N read observed by sample")+ 
  theme_bw()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

```


